<?php
/**
 * Fluent Forms — Set Colors in Email Body
 *
 * Modifies the default color styles used in preformatted email templates generated by Fluent Forms.
 * This allows developers to customize branding and improve visual consistency in outgoing emails
 * without editing core plugin files.
 *
 * @package    FluentFormsSnippets
 * @author     st3phan76
 * @copyright  2026 st3phan76
 * @license    GPL-2.0-or-later
 * @link       https://github.com/st3phan76
 * @version    1.0.0
 */

add_filter('fluentform/email_template_colors', function ($colors) {

    $colors['background_color']      = '#ffffff'; // #f6f6f6 Seitenhintergrund
    $colors['body_background_color'] = '#ffffff'; // #ffffff Tabellenhintergrund
    $colors['base_color']            = '#444444'; // #444444
    $colors['text_color']            = '#444444'; // #444444

    return $colors;

}, 99);

